import dependencies

In [1]:
import pandas as pd # standard python data library
import geopandas as gp # the geo-version of pandas
import numpy as np 
from statistics import mean, median
from pandas import read_csv
import os

Election results from OpenElections (http://openelections.net/)
Shapefile from the Utah Automated Geographic Reference Center (https://gis.utah.gov/data/political/voter-precincts/)

Several transcription errors were corrected from OpenElections using their raw results gathered from counties (https://github.com/openelections/openelections-sources-ut/tree/master/2018%20General%20Election). OE results in Rich and Morgan Counties were based on non-final reports, which were collected from county sources.

Emery County - 8 "canvas votes" were distributed to precincts.

Weber County - 6 precincts had their results suppressed, since all cast fewer than 15 votes, for a total of 42 votes. These were distributed based on the number of votes cast and the reported vote in 2016, which was not suppressed.

G18USSRROM - Mitt Romney (Republican Party)
G18USSDWIL - Jenny Wilson (Democratic Party)
G18USSIMCC - Reed C. McCandless (Independent American Party)
G18USSLBOW - Craig R. Bowden (Libertarian Party)
G18USSCAAL - Tim Aalders (Conservative Party)
G18USSOWRI - Write-in Votes

import files

In [3]:
ut_election_results = pd.read_csv('raw-from-source/20181106__ut__general__precinct.csv')
ut_vest = gp.read_file("raw-from-source/ut_2018/ut_2018.shp")
ut_geo = gp.read_file("raw-from-source/Utah_Vista_Ballot_Areas/VistaBallotAreas.shp")
ut_vest_2016 = gp.read_file("raw-from-source/ut_2016/ut_2016.shp")

In [4]:
display(ut_vest)

,CountyID,mergeid,uniqueid,G18USSRROM,G18USSDWIL,G18USSIMCC,G18USSLBOW,G18USSCAAL,G18USSOWRI,geometry
0,1,BV01,1-BV01,402,46,8,9,19,1,"POLYGON ((358362.560 4238423.840, 358372.350 4..."
1,1,BV02,1-BV02,310,46,3,10,17,0,"POLYGON ((355866.750 4240506.080, 356860.230 4..."
2,1,BV03,1-BV03,244,30,0,2,12,2,"POLYGON ((358902.400 4261055.000, 358909.700 4..."
3,1,BV04,1-BV04,84,7,1,4,23,0,"POLYGON ((367866.500 4262536.100, 367842.500 4..."
4,1,GR01,1-GR01,56,9,6,1,1,1,"POLYGON ((348977.460 4223848.220, 348973.090 4..."
...,...,...,...,...,...,...,...,...,...,...
2332,27,COUN06,27-COUN06,0,0,0,0,0,0,"POLYGON ((255057.190 4154374.220, 256665.370 4..."
2333,27,COUN07,27-COUN07,0,0,0,0,0,0,"POLYGON ((284912.790 4113292.470, 284905.170 4..."
2334,27,SGAIR,27-SGAIR,0,0,0,0,0,0,"POLYGON ((277885.930 4102780.480, 277884.100 4..."
2335,29,LAKE,29-LAKE,0,0,0,0,0,0,"POLYGON ((431658.370 4571461.460, 431647.750 4..."
2336,29,UNKN,29-UNKN,0,0,0,0,0,0,"POLYGON ((419809.790 4559012.840, 419805.010 4..."

In [7]:
display(ut_election_results)

,county,precinct,office,district,candidate,party,votes
0,Wayne,Fremont,U.S. Senate,NaN,Tim Aalders,Con,7
1,Wayne,Loa in/out,U.S. Senate,NaN,Tim Aalders,Con,6
2,Wayne,Lyman in/out,U.S. Senate,NaN,Tim Aalders,Con,6
3,Wayne,Bicknell in/out,U.S. Senate,NaN,Tim Aalders,Con,8
4,Wayne,Teesdale,U.S. Senate,NaN,Tim Aalders,Con,3
...,...,...,...,...,...,...,...
41993,Morgan,Croydon 15.5,U S House,NaN,Rob Bishop,REP,64
41994,Morgan,Croydon 15.5,U S House,NaN,Eric Eliason,UUP,8
41995,Morgan,Croydon 15.5,U S House,NaN,Adam Davis,GRN,2
41996,Morgan,Croydon 15.5,Utah State House,53.0,Logan Wilde,REP,80
41997,Morgan,Croydon 15.5,Utah State House,53.0,Christopher Neville,DEM,6

In [14]:
ut_senators = ut_election_results[(ut_election_results['office'] == 'U.S. Senate') | (ut_election_results['office'] == 'U S Senate')]
county_names = ut_senators['county'].unique()
print(county_names)
county_name_dict = {elem : pd.DataFrame for elem in county_names}
for key in county_name_dict.keys():
    county_name_dict[key] = ut_senators[:][ut_senators.county == key]
print(len(county_name_dict))

['Wayne' 'Salt Lake' 'Wasatch' 'Iron' 'Beaver' 'Utah' 'Carbon' 'Juab'
 'Kane' 'Garfield' 'Daggett' 'Sanpete' 'Sevier' 'Box Elder' 'Grand'
 'Millard' 'San Juan' 'Tooele' 'Duchesne' 'Cache' 'Weber' 'Davis' 'Summit'
 'Uintah' 'Emery' 'Piute' 'Washington' 'Rich' 'Morgan']
29

In [27]:
senators = (ut_senators['candidate'].unique())

In [30]:
pd.options.mode.chained_assignment = None  # default='warn'


def find_votes(name):
    df = (ut_senators[ut_senators['candidate']== name])
    df.votes = pd.to_numeric(df.votes, errors='coerce')
    return (df[df['votes'] > 0])
    

for senator in senators:
    df = find_votes(senator)
    print(senator, 'has a total of', df.votes.sum(), 'in', len(df), 'precincts')

Tim Aalders has a total of 22190.0 in 1263 precincts
Craig Bowden has a total of 13082.0 in 888 precincts
Reed McCandless has a total of 5635.0 in 840 precincts
Jenny Wilson has a total of 142864.0 in 1331 precincts
Mitt Romney has a total of 456966.0 in 1346 precincts
write-in has a total of 721.0 in 293 precincts
MITT ROMNEY has a total of 226341 in 860 precincts
JENNY WILSON has a total of 189902 in 858 precincts
CRAIG R.  BOWDEN has a total of 9854 in 747 precincts
TIM AALDERS has a total of 7941 in 798 precincts
REED C. MCCANDLESS has a total of 4265 in 707 precincts
WRITE-IN has a total of 746 in 420 precincts
CALEB DAN REEVE has a total of 27 in 26 precincts
TYRONE JENSEN has a total of 5 in 4 precincts
GLADE G FITZGERALD has a total of 2 in 2 precincts
HEKTOR REIKSTHEGN has a total of 2 in 2 precincts
CODY JUDY has a total of 2 in 1 precincts
RYAN DANIEL JACKSON has a total of 1 in 1 precincts
ABE KORB has a total of 0 in 0 precincts
Ryan Jackson has a total of 1 in 1 precincts
Craig R. Bowden has a total of 4878 in 370 precincts
Reed C. McCandless has a total of 2822 in 351 precincts
Glade G Fitzgerald (W) has a total of 123 in 1 precincts
Caleb Dan Reeve (W) has a total of 0 in 0 precincts
Hektor Reiksthegn (W) has a total of 0 in 0 precincts
Abe Korb (W) has a total of 0 in 0 precincts
Ryan Daniel Jackson (W) has a total of 0 in 0 precincts
Cody Judy (W) has a total of 0 in 0 precincts
Tyrone Jensen (W) has a total of 0 in 0 precincts
Write In has a total of 12 in 5 precincts
Write-In Totals has a total of 0 in 0 precincts
write-ins has a total of 26 in 15 precincts
Write-In Total has a total of 100 in 21 precincts
CRAIG R. BOWDEN has a total of 522 in 50 precincts
REED C. McCANDLESS has a total of 256 in 43 precincts
Write-ins has a total of 83 in 42 precincts
Write-In has a total of 12 in 6 precincts
CRAIG R BOWDEN has a total of 112 in 27 precincts
REED C MCCANDLESS has a total of 76 in 26 precincts
Caleb Dan Reeve has a total of 1 in 1 precincts
Write-In Votes has a total of 20 in 9 precincts

In [32]:
senator_dict = {}
for senator in senators:
    senator_dict[senator] = None
print(senator_dict)

{'Tim Aalders': None, 'Craig Bowden': None, 'Reed McCandless': None, 'Jenny Wilson': None, 'Mitt Romney': None, 'write-in': None, 'MITT ROMNEY': None, 'JENNY WILSON': None, 'CRAIG R.  BOWDEN': None, 'TIM AALDERS': None, 'REED C. MCCANDLESS': None, 'WRITE-IN': None, 'CALEB DAN REEVE': None, 'TYRONE JENSEN': None, 'GLADE G FITZGERALD': None, 'HEKTOR REIKSTHEGN': None, 'CODY JUDY': None, 'RYAN DANIEL JACKSON': None, 'ABE KORB': None, 'Ryan Jackson': None, 'Craig R. Bowden': None, 'Reed C. McCandless': None, 'Glade G Fitzgerald (W)': None, 'Caleb Dan Reeve (W)': None, 'Hektor Reiksthegn (W)': None, 'Abe Korb (W)': None, 'Ryan Daniel Jackson (W)': None, 'Cody Judy (W)': None, 'Tyrone Jensen (W)': None, 'Write In': None, 'Write-In Totals': None, 'write-ins': None, 'Write-In Total': None, 'CRAIG R. BOWDEN': None, 'REED C. McCANDLESS': None, 'Write-ins': None, 'Write-In': None, 'CRAIG R BOWDEN': None, 'REED C MCCANDLESS': None, 'Caleb Dan Reeve': None, 'Write-In Votes': None}

In [ ]:
# VEST options are: 	G18USSRROM	G18USSDWIL	G18USSIMCC	G18USSLBOW	G18USSCAAL	G18USSOWRI	

senator_dict = {
    'Tim Aalders': 'G18USSCAAL',
    'Craig Bowden': 'G18USSLBOW',
    'Reed McCandless': 'G18USSIMCC',
    'Jenny Wilson': 'G18USSDWIL',
    'Mitt Romney': 'G18USSRROM',
    'write-in': 'G18USSOWRI',
    'MITT ROMNEY': 'G18USSRROM', 
    'JENNY WILSON': 'G18USSDWIL', 
    'CRAIG R.  BOWDEN': 'G18USSLBOW', 
    'TIM AALDERS': 'G18USSCAAL', 
    'REED C. MCCANDLESS': 'G18USSIMCC', 
    'WRITE-IN': 'G18USSOWRI', 
    'CALEB DAN REEVE': 'G18USSOWRI', 
    'TYRONE JENSEN': 'G18USSOWRI', 
    'GLADE G FITZGERALD': 'G18USSOWRI', 
    'HEKTOR REIKSTHEGN': 'G18USSOWRI', 
    'CODY JUDY': 'G18USSOWRI', 
    'RYAN DANIEL JACKSON': 'G18USSOWRI', 
    'ABE KORB': 'G18USSOWRI', 
    'Ryan Jackson': 'G18USSOWRI', 
    'Craig R. Bowden': 'G18USSLBOW', 
    'Reed C. McCandless': 'G18USSIMCC', 
    'Glade G Fitzgerald (W)': 'G18USSOWRI', 
    'Caleb Dan Reeve (W)': 'G18USSOWRI', 
    'Hektor Reiksthegn (W)': 'G18USSOWRI', 
    'Abe Korb (W)': 'G18USSOWRI', 
    'Ryan Daniel Jackson (W)': 'G18USSOWRI', 
    'Cody Judy (W)': 'G18USSOWRI', 
    'Tyrone Jensen (W)': 'G18USSOWRI', 
    'Write In': 'G18USSOWRI', 
    'Write-In Totals': 'G18USSOWRI', 
    'write-ins': 'G18USSOWRI', 
    'Write-In Total': 'G18USSOWRI', 
    'CRAIG R. BOWDEN': 'G18USSLBOW', 
    'REED C. McCANDLESS': 'G18USSIMCC', 
    'Write-ins': 'G18USSOWRI', 
    'Write-In': 'G18USSOWRI', 
    'CRAIG R BOWDEN': 'G18USSLBOW', 
    'REED C MCCANDLESS': 'G18USSIMCC', 
    'Caleb Dan Reeve': 'G18USSOWRI', 
    'Write-In Votes': 'G18USSOWRI'
}